defaults: &defaults
  hotels:
    -
      name: Holiday Inn Express Hotel & Suites Tehachapi
      address: 901 Capital Hills Pkwy, Tehachapi, CA, 93561
      phone: 1-661-822-9837
      rating: 4
      distance: 17.1
      link_to_reservation:  http://www.ihg.com/holidayinnexpress/hotels/us/en/tehachapi/tehca/hoteldetail
      image: hi-express-hotel.jpg
      logo: hi-express-logo.jpg
    -
      name: Fairfield Inn & Suites by Marriott Tehachapi
      address: 422 W Tehachapi Blvd, Tehachapi, CA, 93561
      phone: 1-866-573-4235
      rating: 4
      distance: 15.7
      link_to_reservation: http://www.marriott.com/hotels/travel/bflfi-fairfield-inn-and-suites-tehachapi
      image: fairfield-marriott-hotel.jpg
      logo: fairfield-marriott-logo.jpg
    -
      name: La Quinta Inn Tehachapi
      address: 500 E Steuber Rd, Tehachapi, CA, 93561
      phone: 1-661-823-8000
      rating: 3.5
      distance: 18.6
      link_to_reservation: http://laquintatehachapi.com/
      image: la-quinta-hotel.jpg
      logo: la-quinta-logo.jpg
    -
      name: Best Western Mountain Inn
      address: 418 W Tehachapi Blvd, Tehachapi, CA, 93561
      phone: 1-661-822-5591
      rating: 3.5
      distance: 15.9
      link_to_reservation:  http://book.bestwestern.com/bestwestern/US/CA/Tehachapi-hotels/BEST-WESTERN-Mountain-Inn/Hotel-Overview.do?propertyCode=05424
      image: bw-mountain-inn-hotel.jpg
      logo: bw-mountain-inn-logo.jpg
    -
      name: Best Western Plus Country Park Hotel
      address: 420 W Tehachapi Blvd, Tehachapi, CA, 93561
      phone: 1-661-823-1800
      rating: 3.5
      distance: 15.8
      link_to_reservation: http://bestwesterncalifornia.com/hotels/best-western-plus-country-park-hotel
      image: bw-country-park-hotel.jpg
      logo: bw-country-park-logo.jpg

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

